name: gochilito
favicon: null
layout_spectrum: 0.38729
typography_spectrum: 0.26031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111a1f'
    - '#f9f8f4'
    - '#9f9089'
    - '#385783'
    - '#fb366b'
  brandStrength: 0.8196800479199737
  lightness: 0.8125
  saturation: 0.9355594802182168
  rhythmicContrast: 0.25
purpose: []
